[package]
name = "crayon"
version = "0.1.1"
edition = "2021"
description = "A simple library for rich text in ANSI terminal."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
